sudo: required
dist: trusty
group: edg

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.22.0
    - CACHE_DIR=$HOME/.cache/docker
    - CACHE_FILE_API=$CACHE_DIR/api.tar.gz
    - CACHE_FILE_CLIENT=$CACHE_DIR/client.tar.gz
    - CACHE_FILE_REDIS=$CACHE_DIR/redis.tar.gz
    - CACHE_FILE_POSTGRES=$CACHE_DIR/postgres.tar.gz

cache:
  directories:
    - $CACHE_DIR

before_install:
  - sudo apt update -y
  - sudo apt install --only-upgrade docker-ce -y
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - mkdir -p $CACHE_DIR

install:
  - echo "DEBUG=$DEBUG" >> .env
  - echo "SECRET_KEY=$SECRET_KEY" >> .env
  - echo "USER_ACTIVATION_URI=$USER_ACTIVATION_URI" >> .env
  - echo "USER_PASSWORD_RESET_URI=$USER_PASSWORD_RESET_URI" >> .env
  - echo "DATABASE_URL=$DATABASE_URL" >> .env
  - echo "REDIS_URL=$REDIS_URL" >> .env

  - echo "CODECOV_TOKEN=$CODECOV_TOKEN" >> .env
  - echo "CI=$CI" >> env
  - echo "TRAVIS=$TRAVIS" >> env
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH" >> .env
  - echo "TRAVIS_COMMIT=$TRAVIS_COMMIT" >> .env
  - echo "TRAVIS_JOB_ID=$TRAVIS_JOB_ID" >> .env
  - echo "TRAVIS_JOB_NUMBER=$TRAVIS_JOB_NUMBER" >> .env
  - echo "TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST" >> .env
  - echo "TRAVIS_TAG=$TRAVIS_TAG" >> .env
  - echo "TRAVIS_OS_NAME=$TRAVIS_OS_NAME" >> .env
  - echo "TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG" >> .env
  - export TAG=${TRAVIS_COMMIT::8}

jobs:
  include:
    - stage: Build docker images
      script:
        - if [ -f ${CACHE_FILE_API} ]; then gunzip -c ${CACHE_FILE_API} | docker load; fi
        - make api-build
        - mkdir -p $CACHE_DIR
        - if [ ! -f ${CACHE_FILE_API} ]; then docker save buckets/api:dev | gzip > ${CACHE_FILE_API}; fi
      language: minimal
    - script:
      - if [ -f ${CACHE_FILE_CLIENT} ]; then gunzip -c ${CACHE_FILE_CLIENT} | docker load; fi
      - make client-build
      - mkdir -p $CACHE_DIR
      - if [ ! -f ${CACHE_FILE_CLIENT} ]; then docker save buckets/client:dev | gzip > ${CACHE_FILE_CLIENT}; fi
      language: minimal
    - stage: Tests
      before_script:
        - if [ -f ${CACHE_FILE_API} ]; then gunzip -c ${CACHE_FILE_API} | docker load; fi
        - if [ -f ${CACHE_FILE_CLIENT} ]; then gunzip -c ${CACHE_FILE_CLIENT} | docker load; fi
      script:
        - make up
        - make api-test
        - make api-coverage
      language: minimal
    - script: make up && make client-test
      language: minimal
