coverage:
  status:
    project:
      default:
        target: 100
    patch:
      default:
        target: 100
  range: 95..100
  round: down
  precision: 2
  fixes:
    - "accounts/::api/accounts/"
    - "core/::api/core/"
    - "service_core/::service-core/service_core/"

comment: off