coverage:
  status:
    project:
      default:
        target: 100
    patch:
      default:
        target: 100
  range: 95..100
  round: down
  precision: 2
    fixes:
    - "app/::api/"
    - "client/::client/"

comment: off
