version: '3.3'

services:
  postgres:
    image: postgres:11.1-alpine
    container_name: postgres
    restart: on-failure
    environment:
      - POSTGRES_DB=development
    volumes:
      - database:/var/lib/postgresql
    ports:
      - "5435:5432"

  redis:
    image: redis:3.2-alpine
    container_name: redis
    restart: on-failure
    env_file: ./.env
    ports:
      - "6380:6379"

  web:
    build:
      context: ./app/
    image: cash-miner/web:dev
    container_name: web
    restart: on-failure
    env_file: ./.env
    depends_on:
      - "postgres"
      - "redis"
    volumes:
      - ./app/:/app/
      - node_modules:/app/client/node_modules
    ports:
      - "8000:8000"
      - "8080:8080"

  cypress:
    build:
      context: ./e2e/
    image: cash-miner/cypress:dev
    container_name: cypress
    env_file: ./.env
    depends_on:
      - "web"
    volumes:
      - ./e2e/:/e2e/
    network_mode: 'host'


volumes:
  node_modules:
    driver: local
  database:
    driver: local
