version: '3.3'

services:
  nginx:
    image: buckets/nginx:dev
    container_name: nginx
    restart: always
    volumes:
      - static-data:/static
      - media-data:/media
    ports:
      - "80:80"

  postgres:
    image: buckets/postgres:dev
    container_name: postgres
    restart: always
    env_file: ./env
    volumes:
      - database:/var/lib/postgresql
    ports:
      - "5435:5432"

  redis:
    image: buckets/redis:dev
    container_name: redis
    restart: always
    env_file: ./env
    ports:
      - "6380:6379"

  api:
    image: buckets/api:dev
    container_name: api
    restart: always
    env_file: ./env
    depends_on:
      - "postgres"
      - "redis"
    volumes:
      - static-data:/static
      - media-data:/media
      - ./api/:/app/

volumes:
  database:
    driver: local
  static-data:
    driver: local
  media-data:
    driver: local