version: '3.3'

services:
  postgres:
    image: postgres:11.1-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=development
    volumes:
      - database:/var/lib/postgresql
    ports:
      - "5435:5432"

  redis:
    image: redis:3.2-alpine
    container_name: redis
    restart: always
    env_file: ./.env
    ports:
      - "6380:6379"

  api:
    image: buckets/api:dev
    container_name: api
    restart: always
    env_file: ./.env
    depends_on:
      - "postgres"
      - "redis"
    volumes:
      - ./api/:/app/
    ports:
      - "8000:8000"

  client:
    image: buckets/client:dev
    container_name: client
    restart: always
    env_file: ./.env
    depends_on:
      - "api"
    volumes:
      - ./client:/client/
      - node_modules:/client/node_modules
    ports:
      - "8080:8080"

  e2e:
    image: buckets/e2e:dev
    container_name: e2e
    env_file: ./.env
    depends_on:
      - "client"
    volumes:
      - ./e2e/:/e2e/
    network_mode: 'host'


volumes:
  node_modules:
    driver: local
  database:
    driver: local
