version: '3.3'

services:
  auth:
    container_name: auth
    restart: always
    build: ./auth/
    env_file: ./env
    environment:
      - POSTGRES_DB=auth
    depends_on:
      - "db"
    volumes:
      - static-data:/static
      - media-data:/media
      - ./auth/:/app/
    expose:
      - "8000"

  nginx:
    container_name: proxy
    restart: always
    build: ./nginx/
    depends_on:
      - "auth"
    volumes:
      - static-data:/static
      - media-data:/media
    ports:
      - "80:80"
    expose:
      - "80"

  db:
    container_name: database
    restart: always
    build: ./postgres/
    env_file: ./env
    volumes:
      - database:/var/lib/postgresql
    ports:
      - "5435:5432"
    expose:
      - "5432"

volumes:
  database:
    driver: local
  static-data:
    driver: local
  media-data:
    driver: local