version: '3.3'

services:
  postgres:
    image: postgres:10-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=development
    env_file: ./.env
    volumes:
      - database:/var/lib/postgresql
    ports:
      - "5435:5432"

  redis:
    image: redis:3.2-alpine
    container_name: redis
    restart: always
    env_file: ./.env
    ports:
      - "6380:6379"

  api:
    image: buckets/api:dev
    container_name: api
    restart: always
    env_file: ./.env
    depends_on:
      - "postgres"
      - "redis"
    volumes:
      - ./api/:/app/
    ports:
      - "8000:8000"

  client:
    image: buckets/client:dev
    container_name: client
    restart: always
    env_file: ./.env
    volumes:
      - ./client:/client/
    ports:
      - "8080:8080"

volumes:
  database:
    driver: local
