# Generated by Django 2.0 on 2018-04-11 14:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_pk', models.UUIDField(editable=False)),
                ('user', models.EmailField(blank=True, editable=False, max_length=254, null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('UNDELETE', 'Undelete'), ('DESTROY', 'Destroy')], editable=False, max_length=10)),
                ('serialized_data', models.TextField(editable=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'revision',
                'verbose_name_plural': 'revisions',
                'db_table': 'revision',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='revision',
            index=models.Index(fields=['object_pk', 'content_type', 'user'], name='revision_object__986f73_idx'),
        ),
    ]
