# Generated by Django 2.0 on 2018-04-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('UNDELETE', 'Undelete'), ('DESTROY', 'Destroy')], editable=False, max_length=25),
        ),
    ]
