version: 2
jobs:
  test:
    working_directory: ~/Cash-Miner
    docker:
      - image: circleci/python:3.6.6-node-browsers
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DEBUG: true
          DATABASE_URL: postgresql://root@localhost:5432/circleci?sslmode=disable
          REDIS_URL: redis://localhost:6379/1
      - image: circleci/postgres:11.1-alpine-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circleci
      - image: redis
    steps:
      - checkout
      - run:
          name: Install Django Dependencies
          command: |
            sudo pip install pipenv
            cd api/
            pipenv install --dev
            pipenv shell
      - run:
          name: Install Vue Dependencies
          command: |
            cd client/
            yarn install
      - run:
          name: Up Django Server
          command: |
            cd api/
            python3 manage.py runserver
          background: true
      - run:
          name: Wait Django Server To Be Ready
          command: make health-check
      - run:
          name: Test
          command: make test
      - run:
          name: Coverage
          command: make coverage

  deploy:
    machine: true
    working_directory: ~/Cash-Miner
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: git push heroku master

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
