version: 2
jobs:
  test:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Export env vars
          command: |
            echo "DEBUG=$DEBUG" >> .env
            echo "SECRET_KEY=$SECRET_KEY" >> .env
            echo "DATABASE_URL=$DATABASE_URL" >> .env
            echo "REDIS_URL=$REDIS_URL" >> .env
            echo "CODECOV_TOKEN=$CODECOV_TOKEN" >> .env
            echo "CYPRESS_RECORD_KEY=$CYPRESS_RECORD_KEY" >> .env

            echo "CI=$CI" >> .env
            echo "DISPLAY=$DISPLAY" >> .env
            echo "CIRCLECI=$CIRCLECI" >> .env
            echo "CIRCLE_BRANCH=$CIRCLE_BRANCH" >> .env
            echo "CIRCLE_SHA1=$CIRCLE_SHA1" >> .env
            echo "CIRCLE_BUILD_URL=$CIRCLE_BUILD_URL" >> .env
            echo "CIRCLE_BUILD_NUM=$CIRCLE_BUILD_NUM" >> .env
            echo "CIRCLE_PREVIOUS_BUILD_NUM=$CIRCLE_PREVIOUS_BUILD_NUM" >> .env
            echo "CIRCLE_PULL_REQUEST=$CIRCLE_PULL_REQUEST" >> .env
            echo "CIRCLE_TAG=$CIRCLE_TAG" >> .env
            echo "CIRCLE_PR_NUMBER=$CIRCLE_PR_NUMBER" >> .env
            echo "CIRCLE_PROJECT_REPONAME=$CIRCLE_PROJECT_REPONAME" >> .env
            echo "CIRCLE_PROJECT_USERNAME=$CIRCLE_PROJECT_USERNAME" >> .env
            echo "CIRCLE_REPOSITORY_URL=$CIRCLE_REPOSITORY_URL" >> .env
            echo "CIRCLE_COMPARE_URL=$CIRCLE_COMPARE_URL" >> .env
      - run:
          name: Build images
          command: make build
      - run:
          name: Up services
          command: make up
      - run:
          name: Test
          command: make test
      - run:
          name: Coverage
          command: make coverage

  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Push to Heroku
          command: git push heroku master

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
