# Generated by Django 2.1.7 on 2019-02-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE auth_user SET first_name = (first_name ||' '|| last_name)::varchar(30)"
        ),
        migrations.RemoveField(model_name='user', name='last_name'),
        migrations.RenameField(model_name='user', old_name='first_name', new_name='name')
    ]
