# Generated by Django 2.0.5 on 2018-06-05 21:11

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DESTROY', 'Destroy')], editable=False, max_length=25)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(editable=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'revision',
                'verbose_name_plural': 'revisions',
                'db_table': 'revision',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='revision',
            index=models.Index(fields=['content_type'], name='revision_content_953b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='revision',
            index=django.contrib.postgres.indexes.GinIndex(fields=['data'], name='revision_data_5c2a06_gin'),
        ),
    ]
